"""Output data model produced by every chunker in this package: `Chunk`.

Every strategy (`recursive_overlap`, `hybrid_docling`, `parent_child`, `contextual`)
returns `list[Chunk]` from the same shape, so the embedding/storage pipeline built later
can treat all four interchangeably. `doc_item_refs` is the field that makes image
retrieval possible downstream: it's the set of source DoclingDocument self_refs a chunk
was built from, which `_linking.attach_images()` cross-references against
`ExtractionBundle.pictures`/`.tables` to resolve which saved image files belong with
this chunk -- no vision embedder involved, purely a metadata join.
"""

from __future__ import annotations

import uuid
from typing import Literal, Optional

from pydantic import BaseModel, Field

# Stable namespace for deriving deterministic chunk IDs -- re-chunking the same
# doc+strategy+index reproduces the same chunk_id rather than a new random one, so a
# later embed+upsert step can overwrite instead of duplicate (same pattern as the old
# ingest/shared.py make_point_id, but chunking has no idea Qdrant exists).
_CHUNK_ID_NAMESPACE = uuid.UUID("c5f3e4d6-7c8d-4a9e-8f0a-1b2c3d4e5f6b")


def make_chunk_id(file_hash: str, strategy: str, index: int) -> str:
    key = f"{file_hash}|{strategy}|{index}"
    return str(uuid.uuid5(_CHUNK_ID_NAMESPACE, key))


class ChunkImage(BaseModel):
    """A picture or table crop linked to a chunk -- resolved from ExtractionBundle
    metadata, never generated by the chunker itself."""

    picture_id: str  # self_ref, e.g. "#/pictures/0" or "#/tables/0"
    image_path: str
    caption: Optional[str] = None
    page_no: Optional[int] = None
    kind: Literal["picture", "table"] = "picture"


class Chunk(BaseModel):
    chunk_id: str
    chunk_index: int  # position within this doc+strategy run, for stable ordering/citation

    text: str  # display text, always the raw/unmodified content
    embed_text: str  # what actually gets embedded -- equals `text` unless a strategy
    # enriches it (hybrid/parent_child prepend heading context via contextualize(),
    # contextual prepends an LLM-generated summary sentence)

    strategy: str
    # "text" for ordinary chunks; parent_child labels its two output types; a future
    # image-description enrichment pass would use "image_description".
    kind: Literal["text", "parent", "child", "image_description"] = "text"

    doc_stem: str
    file_hash: str

    page_no: Optional[int] = None
    # Normalized (0..1), top-left-origin (left, top, right, bottom) -- only set for
    # HybridChunker-based strategies (hybrid_docling, parent_child, contextual), which
    # can resolve a single source doc_item's provenance; recursive_overlap's chunks
    # span multiple items with no single well-defined region, so this stays None
    # there. Powers the /documents/{file_hash}/pages/{page_no} grounding endpoint.
    bbox: Optional[tuple[float, float, float, float]] = None
    headings: list[str] = Field(default_factory=list)
    doc_item_refs: list[str] = Field(default_factory=list)
    parent_id: Optional[str] = None  # set on "child" chunks, points at their "parent" chunk_id
    context: Optional[str] = None  # contextual chunker's generated context sentence

    images: list[ChunkImage] = Field(default_factory=list)
